INSERT INTO beers 
(name, tagline, description, first_brewed_at, abv, ibu, ebc, ph, volume, ingredients, brewer_tips, created_at, updated_at) 
VALUES
-- === 12 JÁ EXISTENTES ===
('Skol', 'Desce Redondo', 'Pilsen leve, refrescante e de alta drinkabilidade, uma das mais consumidas no Brasil.', DATE '1964-01-01', 4.7, 8, 5, 4.5, 350, 'malte de cevada, milho, lúpulo', 'Mantenha fermentação baixa para perfil neutro.', NOW(), NOW()),
('Brahma', 'O Sabor de Ser Brahmeiro', 'Pilsen clássica brasileira, corpo leve e sabor suave.', DATE '1888-01-01', 4.8, 10, 6, 4.5, 350, 'malte pilsen, arroz, lúpulo', 'Use maturação prolongada para suavidade.', NOW(), NOW()),
('Antarctica', 'A Boa do Brasil', 'Pilsen tradicional, leve e refrescante, bastante popular em todo o país.', DATE '1885-01-01', 4.8, 11, 6, 4.6, 350, 'malte pilsen, cereais não maltados, lúpulo', 'Carbonatação alta aumenta a refrescância.', NOW(), NOW()),
('Heineken', 'Premium Quality', 'Lager puro malte mundialmente conhecida pelo aroma de lúpulo herbal.', DATE '1873-01-01', 5.0, 20, 7, 4.4, 330, 'malte de cevada, lúpulo, água, levedura A-Yeast', 'Fermente lentamente para perfil mais limpo.', NOW(), NOW()),
('Budweiser', 'King of Beers', 'American Lager com arroz, corpo leve e final seco.', DATE '1876-01-01', 5.0, 12, 6, 4.6, 355, 'malte pilsen, arroz, lúpulo', 'Adicione arroz para leveza característica.', NOW(), NOW()),
('Amstel', '100% Malte', 'Lager puro malte com amargor leve e corpo moderado.', DATE '1870-01-01', 4.6, 18, 7, 4.5, 350, 'malte de cevada, lúpulo', 'Fermentação lenta melhora equilíbrio.', NOW(), NOW()),
('Stella Artois', 'Belgian Premium Lager', 'Lager belga refinada com leve amargor floral e final seco.', DATE '1926-01-01', 5.0, 24, 8, 4.5, 330, 'malte pilsen, lúpulo saaz', 'Use lúpulo nobre para aroma floral.', NOW(), NOW()),
('Itaipava', 'Cerveja 100% Verão', 'Pilsen leve e refrescante, muito consumida no Brasil.', DATE '1993-01-01', 4.5, 10, 5, 4.6, 350, 'malte pilsen, milho, lúpulo', 'Carbonate levemente acima do normal.', NOW(), NOW()),
('Corona', 'La Cerveza Más Fina', 'Mexican Lager clara e suave, famosa por ser servida com limão.', DATE '1925-01-01', 4.5, 10, 4, 4.5, 355, 'malte pilsen, arroz, lúpulo', 'Finalize com limão para realçar frescor.', NOW(), NOW()),
('Guinness Draught', 'Irish Dry Stout', 'A stout irlandesa mais famosa do mundo, com notas de café e chocolate.', DATE '1759-01-01', 4.2, 45, 80, 4.2, 440, 'malte torrado, cevada, lúpulo', 'Nitrogenação deixa o corpo mais cremoso.', NOW(), NOW()),
('Snow Beer', 'Cerveja Mais Vendida da China', 'Lager leve, popular na China pelo sabor suave e refrescante.', DATE '1993-01-01', 4.0, 7, 4, 4.6, 330, 'malte pilsen, arroz, lúpulo', 'Use água de baixa mineralidade.', NOW(), NOW()),
('Tsingtao', 'Cerveja Premium Chinesa', 'Lager premium com leve dulçor e aroma herbal.', DATE '1903-01-01', 4.7, 15, 7, 4.5, 330, 'malte pilsen, arroz, lúpulo saaz', 'Mantenha temperaturas baixas para fermentação limpa.', NOW(), NOW()),

-- === +38 NOVAS PARA TOTALIZAR 50 ===
('Hoegaarden Witbier', 'The Original Belgian Wheat Beer', 'Cerveja de trigo belga refrescante com notas de coentro e casca de laranja.', DATE '1445-01-01', 4.9, 15, 6, 4.6, 330, 'trigo, cevada, coentro, casca de laranja', 'Sirva bem gelada para acentuar o frescor.', NOW(), NOW()),
('Duvel', 'Strong Golden Ale', 'Ale belga forte, dourada e muito aromática.', DATE '1923-01-01', 8.5, 32, 10, 4.6, 330, 'malte pilsen, açúcar, lúpulo', 'Fermente duas vezes para perfil complexo.', NOW(), NOW()),
('Leffe Blonde', 'Belgian Abbey Beer', 'Ale belga suave e frutada com notas de banana e especiarias.', DATE '1240-01-01', 6.6, 20, 10, 4.5, 330, 'malte, lúpulo, especiarias', 'Use fermentação belga tradicional.', NOW(), NOW()),
('Leffe Brune', 'Rich & Dark Abbey Beer', 'Ale escura e maltada com notas de caramelo.', DATE '1240-01-01', 6.5, 22, 35, 4.6, 330, 'maltes escuros, açúcar, lúpulo', 'Maturação prolongada realça dulçor.', NOW(), NOW()),
('Paulaner Weissbier', 'German Wheat Beer', 'Weiss alemã clássica com aroma de banana e cravo.', DATE '1634-01-01', 5.5, 12, 8, 4.7, 500, 'trigo maltado, cevada, lúpulo', 'Evite filtrar para manter turbidez.', NOW(), NOW()),
('Erdinger Weissbier', 'Premium Hefeweizen', 'Weiss alemã leve, refrescante e frutada.', DATE '1886-01-01', 5.3, 10, 8, 4.7, 500, 'trigo, cevada, lúpulo', 'Sirva em copo alto para espuma ideal.', NOW(), NOW()),
('Spaten Lager', 'German Premium Lager', 'Lager alemã equilibrada, suave e fácil de beber.', DATE '1397-01-01', 5.2, 18, 7, 4.7, 500, 'malte pilsen, lúpulo hallertau', 'Mantenha baixa temperatura de maturação.', NOW(), NOW()),
('Beck’s', 'German Quality Beer', 'Lager alemã leve com amargor moderado.', DATE '1873-01-01', 5.0, 20, 7, 4.7, 330, 'malte de cevada, lúpulo, água', 'Use lúpulo alemão para aroma herbal.', NOW(), NOW()),
('Patagonia Amber Lager', 'Cerveja da Patagônia', 'Amber Lager encorpada com notas caramelizadas.', DATE '2010-01-01', 4.5, 18, 20, 4.5, 740, 'malte caramelo, lúpulo', 'Mantenha amargor baixo.', NOW(), NOW()),
('Patagonia Weisse', 'Cerveja de Trigo da Patagônia', 'Weiss leve com notas cítricas.', DATE '2015-01-01', 5.2, 12, 8, 4.6, 740, 'trigo, limão, lúpulo', 'Adicione raspas cítricas no final da fervura.', NOW(), NOW()),
('Colorado Appia', 'Cerveja com Mel', 'Weiss brasileira com adição de mel.', DATE '2005-01-01', 5.5, 12, 10, 4.7, 600, 'trigo, cevada, mel', 'Use mel silvestre para aroma floral.', NOW(), NOW()),
('Colorado Indica', 'India Pale Ale Brasileira', 'IPA brasileira com malte caramelizado e amargor intenso.', DATE '2005-01-01', 7.0, 45, 18, 4.7, 600, 'malte caramelo, lúpulo americano', 'Dry hopping reforça aroma.', NOW(), NOW()),
('Colorado Demoiselle', 'Porter com Café', 'Porter com café brasileiro, sabor intenso.', DATE '2008-01-01', 6.0, 30, 50, 4.4, 600, 'malte torrado, café', 'Use café recém torrado.', NOW(), NOW()),
('Beavertown Gamma Ray', 'American Pale Ale', 'APA explosiva com aroma de frutas tropicais.', DATE '2011-01-01', 5.4, 45, 12, 4.5, 330, 'malte, lúpulo americano', 'Dry hopping generoso.', NOW(), NOW()),
('Beavertown Neck Oil', 'Session IPA', 'IPA leve e extremamente refrescante.', DATE '2012-01-01', 4.3, 35, 10, 4.5, 330, 'malte, lúpulo cítrico', 'Dry hopping leve para refrescância.', NOW(), NOW()),
('Goose Island IPA', 'India Pale Ale', 'IPA americana clássica, aromática e equilibrada.', DATE '1995-01-01', 5.9, 55, 13, 4.5, 355, 'malte, lúpulo cítrico', 'Use lúpulos Cascade e Centennial.', NOW(), NOW()),
('Goose Island Midway', 'Session IPA', 'IPA leve com notas cítricas e tropicais.', DATE '2016-01-01', 4.1, 30, 10, 4.6, 350, 'malte, lúpulo americano', 'Amargor moderado para beber fácil.', NOW(), NOW()),
('Guinness Extra Stout', 'Irish Stout', 'Versão mais amarga e encorpada da Guinness clássica.', DATE '1821-01-01', 5.6, 50, 90, 4.3, 500, 'malte torrado, cevada, lúpulo', 'Use malte torrado a frio.', NOW(), NOW()),
('Guinness Foreign Extra', 'Export Stout', 'Stout potente, amarga e intensa.', DATE '1801-01-01', 7.5, 60, 100, 4.3, 500, 'malte torrado, cevada, lúpulo', 'Mais lúpulo para exportação.', NOW(), NOW()),
('Hoegaarden Rosée', 'Belgian Fruit Beer', 'Witbier com adição de frutas vermelhas.', DATE '2007-01-01', 3.0, 8, 5, 4.4, 250, 'trigo, frutas vermelhas', 'Sirva bem gelada.', NOW(), NOW()),
('Kwak', 'Belgian Strong Ale', 'Ale belga forte com notas de caramelo e especiarias.', DATE '1791-01-01', 8.4, 20, 30, 4.6, 330, 'malte especial, lúpulo', 'Use copo tradicional Kwak.', NOW(), NOW()),
('La Trappe Dubbel', 'Trappist Beer', 'Ale trapista escura, maltada e complexa.', DATE '1884-01-01', 7.0, 25, 40, 4.6, 330, 'malte caramelo, lúpulo', 'Fermente mais quente.', NOW(), NOW()),
('La Trappe Tripel', 'Trappist Beer', 'Ale dourada forte, frutada e aromática.', DATE '1934-01-01', 8.0, 30, 15, 4.5, 330, 'malte, lúpulo aromático', 'Use açúcar para corpo leve.', NOW(), NOW()),
('Chimay Red', 'Trappist Dubbel', 'Ale trapista encorpada com notas de frutas secas.', DATE '1862-01-01', 7.0, 23, 40, 4.6, 330, 'malte especial', 'Maturação longa.', NOW(), NOW()),
('Chimay Blue', 'Belgian Strong Dark Ale', 'Ale escura poderosa com notas de caramelo e especiarias.', DATE '1948-01-01', 9.0, 35, 60, 4.6, 330, 'malte escuro, lúpulo', 'Melhora com envelhecimento.', NOW(), NOW()),
('Delirium Tremens', 'Belgian Strong Ale', 'Famosa pela garrafa com elefantes rosas.', DATE '1989-01-01', 8.5, 26, 10, 4.5, 330, 'malte claro, lúpulo nobre', 'Fermentação especial.', NOW(), NOW()),
('Delirium Nocturnum', 'Belgian Strong Dark Ale', 'Versão escura e encorpada da Delirium.', DATE '1999-01-01', 8.5, 30, 50, 4.5, 330, 'malte escuro', 'Sabor profundo.', NOW(), NOW()),
('Weihenstephaner Hefeweissbier', 'The World’s Oldest Brewery', 'Weiss clássica alemã macia e frutada.', DATE '1040-01-01', 5.4, 14, 8, 4.5, 500, 'trigo, cevada', 'Tenha cuidado com a espuma.', NOW(), NOW()),
('Weihenstephaner Vitus', 'Weizenbock', 'Cerveja de trigo forte, encorpada e doce.', DATE '2007-01-01', 7.7, 17, 15, 4.5, 500, 'trigo, malte especial', 'Fermentação mais quente.', NOW(), NOW()),
('Schneider Weisse Original', 'Hefeweizen', 'Weiss alemã encorpada com notas de banana e especiarias.', DATE '1872-01-01', 5.4, 14, 10, 4.5, 500, 'trigo maltado, cevada', 'Não filtre.', NOW(), NOW()),
('Schneider Aventinus', 'Weizenbock', 'Cerveja forte de trigo com notas de ameixa e chocolate.', DATE '1907-01-01', 8.2, 20, 40, 4.6, 500, 'trigo, malte escuro', 'Maturação prolongada.', NOW(), NOW()),
('Modelo Especial', 'Mexican Lager', 'Lager mexicana premium com sabor suave.', DATE '1925-01-01', 4.5, 10, 5, 4.5, 355, 'malte pilsen, milho, lúpulo', 'Sirva gelada.', NOW(), NOW()),
('Pacifico Clara', 'Mexican Lager', 'Lager leve e refrescante.', DATE '1900-01-01', 4.5, 12, 5, 4.6, 355, 'malte pilsen, milho, lúpulo', 'Muito refrescante.', NOW(), NOW()),
('Blue Moon', 'Belgian White', 'Witbier americana com casca de laranja.', DATE '1995-01-01', 5.4, 9, 5, 4.6, 355, 'trigo, casca de laranja', 'Sirva com rodela de laranja.', NOW(), NOW()),
('Samuel Adams Boston Lager', 'American Lager', 'Lager encorpada com notas florais e tostadas.', DATE '1984-01-01', 5.0, 30, 10, 4.7, 355, 'malte especial, lúpulo nobre', 'Maltagem cuidadosa.', NOW(), NOW()),
('Brooklyn Lager', 'Amber Lager', 'Lager âmbar de Nova York com aroma floral.', DATE '1988-01-01', 5.2, 30, 15, 4.6, 355, 'malte caramelo, lúpulo americano', 'Dry hopping leve.', NOW(), NOW());
